on:
  push:
    branches: [ main, ops]

jobs:
  build:
    runs-on: ubuntu-22.04
    env: 
      REGISTRY_PATH: g4rr0u
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login docker registry
        run: |
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push image
        run: |
          echo "Start building"
          docker build -t ${{ env.REGISTRY_PATH }}/nginx:latest .
          docker push ${{ env.REGISTRY_PATH }}/nginx:latest
          docker logout || true

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    env:
      REGISTRY_PATH: g4rr0u
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: | 
            docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}
            docker pull ${{ env.REGISTRY_PATH }}/nginx:latest
            docker stop nzr_nginx || true
            docker rm --force nzr_nginx || true
            docker run -d --name nzr_nginx --restart always -p 8080:8080 ${{ env.REGISTRY_PATH }}/nginx:latest
            docker logout || true
            